name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps: 
      - id: short_sha
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - id: test_sha_short
        run: echo '${{ steps.short_sha.outputs.sha_short }}'
      - id: test_GITHUB_TOKEN
        run: echo '${{ secrets.GITHUB_TOKEN }}'
      - id: create_issue
        run: |
          curl --request POST \
          --url https://api.github.com/repos/ThomasM-Sfeir/sfeir-school-github-actions/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{"title":"Issue ${{ steps.short_sha.outputs.sha_short }}","body":"Let'\''s try the issue generation.","milestone":1,"labels":["bug"]}' \
          --fail