name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps: 
      - id: Short the SHA
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - id: Create the issue
        run: curl -L \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ GITHUB_TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/ThomasM-Sfeir/sfeir-school-github-actions/issues \
                  -d '{"title":"Automatic issue !","body":"Let'\''s try the issue generation.","assignees":["ThomasM-Sfeir"],"milestone":1,"labels":["bug"]}'