name: test workflow
on: 
  workflow_dispatch:

jobs:
  caller-workflow:
    uses: https://github.com/ThomasM-Sfeir/sfeir-school-github-actions/blob/main/.github/workflows/exercice3.yaml
    with:
      node-version: '20'